export default {
  english: {
    HomeHeaderGold: "Gold Prices",
    AssetsSrcHeaderTitle: "Assets",
    HomeSrcHeaderTitle: "Home Page",
    OthersSrcHeaderTitle: "Other Services",
    GoldSrcHeaderTitle: "Gold",
    CurrencySrcHeaderTitle: "Currency",
    CalculateSrcHeaderTitle: "Calculate",
    ExchangeSrcHeaderTitle: "Cross Currencies",
    NewsSrcHeaderTitle: "News",
    ZakatCalculateHeaderTitle: "Zakat Calculater",
    OptionsHeaderTitle: "Options",
    type: "Type",
    buying: "Buying",
    selling: "Selling",
    ratio: "Ratio %",
    gold: "Gold",
    Currency: "Currency",
    ChartScrHeaderTitle: "Chart",
    GoldCurrencyCalculateHeaderTitle: "Gold-Currency Calculate",
    SarrafiSrcHeaderTitle: "Sarrafiye Price",
    CalculateBottomTabLabel: "Calculate",
    CryptoSrcHeaderTitle: "Crypto",
    Quantity: "Quantity",
    rate: "Rate",
    noTypeAlertText: "Please select a rate type",
    noTypeAlertTextHeader: "Type Error!",
    Ok: "Ok",
    Now: "Now ",
    Code: "Code:",
    DateofBuy: "Buy Date:",
    BoughtPrice: "Bought Price:",
    TotalMoney: "Money:",
    ProfitAndLoss: "Prof/Loss:",
    calculating: "Calculating...",
    AssetFirstStep: "Select a type",
    QuantityRequest: "Please write quantities",
    AssetThirdStep: "Choose Date",
    AssetButtonText: "My Assets",
    AssetAddButtonText: "Add Asset",
    Saved: "Saved",
    AddNewAsset: "Add New Asset",
    Details: "Details",
    ChartScreenErrorText1: "We can't access chart datas.",
    ChartScreenErrorText2: "Why could it be?",
    ChartScreenErrorText3: "Stock market may be closed.",
    ChartScreenErrorText4: "This entities hasn't old datas ",
    ChartScreenErrorText5: "There may be a problem with your internet",
    ChartScreenErrorText6: "You may try next time",
    Price: "Price",
    selected: "Your selection is ",
    Login: "Login",
    Unit: "Unit",
    Date: "Date",
    Hour: "Hour",
    Account: "Account",
    Add: "Add",
    equals: "Equals",
    RetroScreenName: "Retrospective",
    ifITook: "if I Took",
    ifISold: "if I Sold",
    Reset: "Reset",
    received: "Received",
    ifISell: "if I Sell",
    ClickForCreateNewAsset: "Click to create a new asset",
    createAsset: "Create Asset",
    t_Q: "T/Q",
    nowRate: "Now Rate",
    Cost: "Cost",
    Result: "Result",
    LastPrice: "Last Price :",
    HighestValue: "Highest value",
    LowestValue: "LowestValue",
    NoAlarm: "There is no saved alarm",
    BTV: "Below The Value",
    ATV: "Above The Value",
    CheckYourInputs:"Please Check your inputs.",
    Note: "Note...",
    setAnAlarm: "Set an Alarm",
    openAnAlarm: "All Alarms Off",
    openAlarmText: "You have to turn on least one alarm",
    valueAlarm: "Value Error",
    valueAlarmText: "Both of the value can not be 0",
    checkValueText: "Please Check Your values",
    checkYourInputs: "- Check Your Inputs -",
    Username: "Username",
    Password: "Password",
    RMA:"The remaining amount",
    Buy:"Buy",
    Sell:"Sell",
    SuccessfulOperation: "Operation Success",
    ChangePasswordText:"Your password changed",
    FailedOperation: "Operation Failed",
    Name:"Name",
    Surname:"Surname",
    Company:"Company",
    PhoneNumber:"Phone Number",
    province:"Province",
    district:"District",
    address:"Address",
    SavePassword:"Save Password",
    TopBarTitle:"Top Bar Values",
    ZakatAlarmText:"Please Select a Zakat Value",
    AddAgain:"Add Again",
    total:"Total",
    Zekat:"Zakat",
    LoginText:"Please Login",



  },
  turkish: {
    HomeHeaderGold: "Altın Fiyatları",
    AssetsSrcHeaderTitle: "Varlıklarım",
    OthersSrcHeaderTitle: "Diğer Hizmetlerimiz",
    GoldSrcHeaderTitle: "Altın",
    CheckYourInputs:"Lütfen Bilgilerinizi kontrol ediniz.",
    HomeSrcHeaderTitle: "Ana Sayfa",
    CurrencySrcHeaderTitle: "Döviz",
    CalculateSrcHeaderTitle: "Kar / Zarar Hesaplama",
    ZakatCalculateHeaderTitle: "Zekat Hesaplama",
    ExchangeSrcHeaderTitle: "Çapraz Kurlar",
    NewsSrcHeaderTitle: "Haberler",
    OptionsHeaderTitle: "Ayarlar",
    type: "Tür",
    buying: "Alış",
    selling: "Satış",
    ratio: "Oran %",
    gold: "Altın",
    Currency: "Para Birimi",
    ChartScrHeaderTitle: "Grafik",
    GoldCurrencyCalculateHeaderTitle: "Altın / Döviz Çevirici",
    SarrafiSrcHeaderTitle: "Sarrafi İşçilikleri",
    CalculateBottomTabLabel: "Hesaplama",
    CryptoSrcHeaderTitle: "Kripto",
    Quantity: "Miktar",
    rate: "Kur",
    noTypeAlertText: "Bir varlık seçiniz Örn: Dolar",
    noTypeAlertTextHeader: "Tür Hatası!",
    Ok: "Tamam",
    Now: "Anlık ",
    Code: "Kodu:",
    DateofBuy: "Alım Tarihi:",
    BoughtPrice: "Alım Kuru:",
    TotalMoney: "Toplam ",
    ProfitAndLoss: "Kar/Zarar:",
    calculating: "Hesaplanıyor...",
    AssetFirstStep: "Tür Seçiniz",
    QuantityRequest: "Miktar Giriniz",
    AssetThirdStep: "Tarih Seçiniz",
    AssetButtonText: "Varlıklarıma Git",
    AssetAddButtonText: "Varlık Ekle",
    Saved: "Kaydedildi",
    AddNewAsset: "Yeni Varlık Ekle",
    Details: "Detay",
    ChartScreenErrorText1: "Grafik Verilerine Erişemiyoruz",
    ChartScreenErrorText2: "Neden olabilir?",
    ChartScreenErrorText3: "Borsa kapalı Olabilir.",
    ChartScreenErrorText4: "Bu varlığın geçmiş verileri yoktur.",
    ChartScreenErrorText5: "İnternetiniz ile ilgili bir problem olabilir.",
    ChartScreenErrorText6: "Daha sonra tekrar deneyebilirsiniz.",
    Price: "Fiyat",
    selected: "Seçiminiz: ",
    Login: "Giriş Yap",
    Unit: "Birim",
    Date: "Tarih",
    Hour: "Saat",
    Account: "Hesabım",
    Add: "Ekle",
    equals: "Karşılığı",
    RetroScreenName: "Geçmişe Yönelik Hesaplama",
    ifITook: "Alsaydım",
    ifISold: "Satsaydım",
    Reset: "Sıfırla",
    received: "Aldığım",
    ifISell: "Satarsam",
    ClickForCreateNewAsset: "Yeni bir varlık oluşturmak için tıklayınız.",
    createAsset: "Varlık Oluştur",
    t_Q: "B/M",
    nowRate: "Şimdiki Kur",
    Cost: "Maliyet",
    Result: "Sonuç",
    LastPrice: "SON FİYAT :",
    HighestValue: "En Yüksek",
    LowestValue: "En Düşük",
    NoAlarm: "Kaydedilen Alarm Yok...",
    BTV: "Altına İnerse",
    ATV: "Üstüne Çıkarsa",
    Note: "Not...",
    setAnAlarm: "Alarm Kur",
    openAnAlarm: "Alarm Açmadınız",
    openAlarmText: "Bir alarm açınız.",
    valueAlarm: "Değer Hatası",
    valueAlarmText: "İki değer de 0 olamaz",
    checkValueText: "Üst değer ve Alt değerinizi kontrol ediniz.",
    checkYourInputs: "- Hatalı Giriş -",
    Username: "Kullanıcı Adı",
    Password: "Şifre",
    RMA:"Kalan miktar",
    Buy:"Al",
    Sell:"Sat",
    SuccessfulOperation: "İşlem Başarılı",
    ChangePasswordText:"Şifreniz Değiştirildi",
    FailedOperation: "İşlem Başarısız",
    Name:"Ad",
    Surname:"Soyad",
    Company:"Firma",
    PhoneNumber:"Tel",
    province:"İl",
    district:"İlçe",
    address:"Adres",
    SavePassword:"Şifreyi Kaydet",
    TopBarTitle:"Takip",
    ZakatAlarmText:"Zekat Değeri Seçiniz.",
    AddAgain:"Yeniden Ekle",
    total:"Toplam",
    Zekat:"Zekat",
    LoginText:"Giriş Yapınız",
    
  },
};
